# Generated by Django 2.1.5 on 2019-02-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190212_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
